#!/bin/sh

set -eu

exec 2>&1

modprobe tiatm

I=0
while true; do
	grep -q SHOWTIME /proc/avalanche/avsar_modem_training && break

	if [ $I -eq 120 ]; then
		echo ADSL did not sync >&2
		exit 1
	fi

	sleep 1

	I=$((I+1))
done

if grep -q rp-pppoe /etc/ppp/options; then
	ifup nas0

	modprobe pppoe
else
	modprobe pppoatm
fi

exec pppd
