#!/bin/sh

set -eu

exec 2>&1

modprobe tiatm

I=0
while true; do
	grep -q SHOWTIME /proc/avalanche/avsar_modem_training && break

	[ $I -eq 120 ] && echo no sync after 120s, retrying silently >&2

	sleep 1

	I=$((I+1))
done

if grep -q rp-pppoe /etc/ppp/options; then
	ifup nas0

	modprobe pppoe
else
	modprobe pppoatm
fi

exec pppd
