#!/bin/sh

set -eu

exec 2>&1
exec /usr/sbin/dnsmasq \
	--keep-in-foreground \
	--interface eth0 \
	--auth-server=%DOMAIN%,ppp0 \
	--bind-interfaces \
	--bogus-priv \
	--resolv-file=/etc/ppp/resolv.conf \
	--stop-dns-rebind \
	--rebind-localhost-ok \
	--domain-needed \
	--dhcp-range=%DHCPS%,%DHCPF%,48h \
	--dhcp-range=%WAN6NT%:%LAN6NT%::,ra-stateless,ra-names \
	--dhcp-authoritative \
	--dhcp-leasefile=/var/run/dnsmasq.leases \
	--domain=%DOMAIN%,%LAN4IP%/24,local \
	--enable-ra
