#!/bin/sh

set -eu

exec 2>&1
exec /usr/sbin/dnsmasq \
	--keep-in-foreground \
	--interface eth0 \
	--auth-server=ns.%DOMAIN%,ppp0 \
	--host-record=ns.%DOMAIN%,%WAN4IP%,%WAN6NT%:: \
	--auth-zone=digriz.wormnet.eu,%WAN4IP%,%WAN6NT%::/48 \
	--bogus-priv \
	--stop-dns-rebind \
	--rebind-localhost-ok \
	--domain-needed \
	--dhcp-range=%DHCPS%,%DHCPF%,48h \
	--dhcp-range=%WAN6NT%:%LAN6NT%::,ra-stateless,ra-names \
	--dhcp-authoritative \
	--dhcp-leasefile=/var/run/dnsmasq.leases \
	--domain=%DOMAIN%,%LAN4IP%/24,local \
	--enable-ra
