#!/bin/sh

set -eu

DEV=$(basedir $(dirname $0))
BAUD=38400

exec </dev/$DEV >/dev/$DEV 2>&1

reset
stty sane; stty ispeed $BAUD; stty ospeed $BAUD

printf "%s login: " "`hostname`"
read -r login

exec /bin/login "$login"
